yatube/posts/urls.py
"""Urls for app posts.
"""
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_list')
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('group/<slug:slug>/', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls)
]

yatube/posts/models.py
"""Models for database: Group, Post.
"""
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()


class Group(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    description = models.TextField()

    def __str__(self):
        return self.title


class Post(models.Model):
    text = models.TextField()
    pub_date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts'
    )
    group = models.ForeignKey(
        Group,
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        related_name='posts'
    )

    class Meta:
        ordering = ['-pub_date', ]

yatube/posts/views.py
"""Views for app posts.
"""
from django.shortcuts import render, get_object_or_404


from .models import Post, Group

POST_LIMIT = 10


# Main page
def index(request):
    template = 'posts/index.html'
    title = 'Последние обновления на сайте.'
    posts = Post.objects.all()[:POST_LIMIT]
    context = {
        'title': title,
        'posts': posts,
    }
    return render(request, template, context)


# Guests page
def group_posts(request, slug):
    template = 'posts/group_list.html'
    title = f'Записи сообщества {get_object_or_404(Group, slug=slug)}'
    group = get_object_or_404(Group, slug=slug)
    posts = group.posts.all()[:POST_LIMIT]
    context = {
        'title': title,
        'group': group,
        'posts': posts,
    }
    return render(request, template, context)

yatube/templates/base.html
{% load static %}
<!DOCTYPE html> 
<html lang="ru">
  <head>    
    {% include 'includes/head.html' %}
    <title>{% block title %}Title{% endblock %}</title>
  </head>
  <body>       
    <header>
      {% include 'includes/header.html' %}
    </header>
    <main>
      <div class="container py-5"> 
      {% block content %}
        Контент не подвезли :(
      {% endblock %}
      </div> 
    </main>
    <footer class="border-top text-center py-3">
      {% include 'includes/footer.html' %} 
    </footer>
  </body>
</html> 

yatube/templates/includes/author_date_post.html
{% load static %}
<ul>
    <li>
    Автор: {{ post.author.get_full_name }}
    </li>
    <li>
    Дата публикации: {{ post.pub_date|date:"d E Y" }}
    </li>
</ul>
<p>{{ post.text }}</p>

yatube/templates/includes/footer.html
{% load static %}
<p>© {% now "Y" %} Copyright <span style="color:red">Ya</span>tube</p>     
 

yatube/templates/includes/head.html
{% load static %}
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="icon" href="img/fav/fav.ico" type="image">
<link rel="apple-touch-icon" sizes="180x180" href="img/fav/apple-touch-icon.png">
<link rel="icon" type="image/png" sizes="32x32" href="img/fav/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="16x16" href="img/fav/favicon-16x16.png">
<meta name="msapplication-TileColor" content="#000">
<meta name="theme-color" content="#ffffff">
<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">

yatube/templates/includes/header.html
{% load static %}
<nav class="navbar navbar-light" style="background-color: lightskyblue">
<div class="container">
    <a class="navbar-brand" href="{% url 'posts:index' %}">
    <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
    <span style="color:red">Ya</span>tube
    </a>
</div>
</nav>   

yatube/templates/posts/group_list.html
<!-- templates/posts/group_list.html -->
{% extends 'base.html' %}
{% load static %}
{% block title %}{{ title }}{% endblock %}
{% block content %}
{{ content }}
<!-- group name -->
<h1>{{ group.title }}.</h1>
        <p>
            <!-- group description -->
            {{ group.description }}
        </p>
{% for post in posts %}
{% include 'includes/author_date_post.html' %} 
{% if not forloop.last %}<hr>{% endif %}
{% endfor %}
{% endblock %}  

yatube/templates/posts/index.html
<!-- templates/posts/group_list.html -->
{% extends 'base.html' %}
{% load static %}
{% block title %}{{ title }}{% endblock %}
{% block content %}
{{ content }}
{% for post in posts %}
{% include 'includes/author_date_post.html' %}  
  {% if post.group %}   
    <a href="{% url 'posts:group_list' post.group.slug %}">
      #{{ post.group.title }}
    </a>
  {% endif %}
{% if not forloop.last %}<hr>{% endif %}
{% endfor %}
{% endblock %} 